
brave.exe is not running
Quit was selected. Confirm with 'Q' within 1 minute to delete the script.
30 seconds left
10 seconds left
0 seconds left
Deleting the script
Starting up at 17:06:27
Script path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Script directory: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
Tr path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Tr moved to: None
Cleaner path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\cleaner.exe
An error occurred: move_cleaner_to_programs() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "tr.py", line 122, in main
TypeError: move_cleaner_to_programs() takes 1 positional argument but 2 were given

Starting up at 19:18:57
Script path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Script directory: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
Tr path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Tr moved to: None
Cleaner path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\cleaner.exe
An error occurred: move_cleaner_to_programs() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "tr.py", line 122, in main
TypeError: move_cleaner_to_programs() takes 1 positional argument but 2 were given

Starting up at 19:10:37
Script path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Script directory: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
Tr path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Cleaner path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\cleaner.exe
An error occurred: move_cleaner_to_programs() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "tr.py", line 122, in main
TypeError: move_cleaner_to_programs() takes 1 positional argument but 2 were given

Starting up at 17:03:28
Script path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Script directory: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
Tr path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Tr moved to: None
Cleaner path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\cleaner.exe
An error occurred: move_cleaner_to_programs() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "tr.py", line 122, in main
TypeError: move_cleaner_to_programs() takes 1 positional argument but 2 were given

Script path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Script directory: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
Tr path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Tr moved to: None
Cleaner path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\cleaner.exe
An error occurred: move_cleaner_to_programs() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "tr.py", line 122, in main
TypeError: move_cleaner_to_programs() takes 1 positional argument but 2 were given

Starting up at 14:15:11
Script path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Script directory: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
An error occurred: 409 {"message": "output does not match f24bb5da06710ec7857d9bba7539a8c8f00b477d", "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
Traceback (most recent call last):
  File "tr.py", line 116, in main
  File "tr.py", line 44, in print_to_github
  File "tr.py", line 39, in update_file
  File "github\Repository.py", line 2242, in update_file
  File "github\Requester.py", line 398, in requestJsonAndCheck
  File "github\Requester.py", line 423, in __check
github.GithubException.GithubException: 409 {"message": "output does not match f24bb5da06710ec7857d9bba7539a8c8f00b477d", "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}

Starting up at 19:43:44
Script path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Script directory: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
Tr path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Tr moved to: None
Cleaner path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\cleaner.exe
An error occurred: move_cleaner_to_programs() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "tr.py", line 122, in main
TypeError: move_cleaner_to_programs() takes 1 positional argument but 2 were given

Starting up at 14:21:49
Script path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Script directory: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
Tr path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Tr moved to: None
Cleaner path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\cleaner.exe
An error occurred: move_cleaner_to_programs() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "tr.py", line 122, in main
TypeError: move_cleaner_to_programs() takes 1 positional argument but 2 were given

Starting up at 21:50:56
Script path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Script directory: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
Tr path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Tr moved to: None
Cleaner path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\cleaner.exe
An error occurred: move_cleaner_to_programs() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "tr.py", line 122, in main
TypeError: move_cleaner_to_programs() takes 1 positional argument but 2 were given

Starting up at 10:52:27
Script path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Script directory: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
Tr path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Tr moved to: None
Cleaner path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\cleaner.exe
An error occurred: move_cleaner_to_programs() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "tr.py", line 122, in main
TypeError: move_cleaner_to_programs() takes 1 positional argument but 2 were given

Starting up at 15:36:57
Script path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Script directory: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup
Tr path: C:\Users\thasi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\tr.exe
Tr moved to: None
